### ISSUE TITLE
Add DB support

### ISSUE THREAD

**Issue by alexmikhalevich** [maked0n/RoadToGoal#1]
Example can be found here: https://developer.android.com/training/data-storage/room/.
For the first time the DB should contain cards which have names and background pictures.

**Comment by annsheronova** [comment]
1. GoalEntity (которая в бд) и  Goal (которую показываем пользователю) одна и та же сущность?
Если нет, то с помощью чего мапить?
2. Определиться с полями в бд

**Comment by alexmikhalevich** [comment]
1. Есть Goal и над ней сколь угодно много декораторов для каждой цели.
2. Пока что id, name, backpic (background picture).
